=== Financial-Times/vulnerability-dashboard-api-schema-public/schema/system.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "description": "Number of findings for individual system",
  "$ref": "#/definitions/System",
  "definitions": {
    "System": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer",
          "description": "System product id found in DefectDojo"
        },
        "code": {
          "type": "string",
          "description": "The unique identification (systemcode) for this system found in BizOps"
        },
        "findingsCount": {
          "type": "integer",
          "description": "The number of findings found in DefectDojo"
        },
        "findingsList": {
          "type": "array",
          "description": "A list of finding ID's that correlate to findings found in DefectDojo",
          "items": {
            "type": "integer"
          }
        },
        "teamId": {
          "type": "integer",
          "description": "Product Type ID found in DefectDojo"
        },
        "serviceTier": {
          "type": "string",
          "description": "The service tier (level of support) given to this system found in BizOps"
        },
        "lifecycle": {
          "type": "string",
          "description": "DefectDojo's version of system lifecycle, which reduces the BizOps lifecycle stages down to either Construction, Production or Retirement"
        },
        "bizOpsLifecycleStage": {
          "type": "string",
          "description": "How far this system has progressed through its lifecycle from Preproduction to Decommissioned found in BizOps"
        },
        "scanTypes": {
          "type": "array",
          "description": "A list of scanners that have scanned system found in DefectDojo",
          "items": {
            "type": "string"
          }
        },
        "findings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Finding"
          }
        },
        "snykProjects": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/SnykProject"
          }
        },
        "matchingSnykFindingsCount": {
          "type": "integer"
        },
        "totalFindings": {
          "type": "integer"
        },
        "findingsOverSla": {
          "$ref": "#/definitions/FindingsOverSla"
        }
      },
      "required": [
        "code",
        "findings",
        "findingsCount",
        "findingsList",
        "findingsOverSla",
        "id",
        "lifecycle",
        "matchingSnykFindingsCount",
        "scanTypes",
        "serviceTier",
        "snykProjects",
        "teamId",
        "totalFindings"
      ],
      "title": "System"
    },
    "Finding": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer",
          "description": "Finding ID found in DefectDojo"
        },
        "name": {
          "type": "string",
          "description": "Name of finding found in DefectDojo"
        },
        "age": {
          "type": "string",
          "description": "How long finding has been open"
        },
        "active": {
          "type": "boolean",
          "description": "Finding status weather it is currently exploitable"
        },
        "severity": {
          "$ref": "#/definitions/Severity"
        },
        "created": {
          "type": "string",
          "description": "Date and time when finding was created in DefectDojo"
        },
        "foundBy": {
          "$ref": "#/definitions/FoundBy"
        },
        "remediation": {
          "description": "The action of fixing the vulnerability",
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "string"
            }
          ]
        },
        "ageDays": {
          "type": "integer",
          "description": "Number of days old for finding"
        },
        "link": {
          "type": "string",
          "description": "URL to finding in DefectDojo"
        },
        "hasRemediation": {
          "type": "boolean",
          "description": "Check if there is an action to fix vulnerability"
        }
      },
      "required": [
        "active",
        "age",
        "ageDays",
        "created",
        "foundBy",
        "hasRemediation",
        "id",
        "link",
        "name",
        "remediation",
        "severity"
      ],
      "title": "Finding"
    },
    "FindingsOverSla": {
      "type": "object",
      "description": "Number of findings grouped by severity that have gone pass sla - https://docs.google.com/document/d/1XXfYyNG5Qvtxb-hE7o4MhYWxZarQEe8hby38a8bOq4w",
      "additionalProperties": false,
      "properties": {
        "medium": {
          "type": "integer"
        },
        "low": {
          "type": "integer"
        },
        "high": {
          "type": "integer"
        },
        "critical": {
          "type": "integer"
        }
      },
      "required": [],
      "title": "FindingsOverSla"
    },
    "SnykProject": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string",
          "description": "ID of Snyk project"
        },
        "name": {
          "type": "string",
          "description": "Name of Snyk project"
        },
        "created": {
          "type": "string",
          "description": "Date and time for when snyk project was created"
        },
        "origin": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "readOnly": {
          "type": "boolean"
        },
        "testFrequency": {
          "type": "string"
        },
        "isMonitored": {
          "type": "boolean",
          "description": "Check if snyk project is continuously monitored for open source vulnerabilities and license issues"
        },
        "totalDependencies": {
          "type": "integer",
          "description": "Total number of dependencies in snyk project"
        },
        "issueCountsBySeverity": {
          "$ref": "#/definitions/IssueCountsBySeverity"
        },
        "imageTag": {
          "type": "string"
        },
        "imagePlatform": {
          "type": "string"
        },
        "imageBaseImage": {
          "type": "string"
        },
        "lastTestedDate": {
          "type": "string",
          "description": "Date and time when snyk last scanned depedencies"
        },
        "browseUrl": {
          "type": "string",
          "description": "URL to Snyk Project"
        },
        "owner": {
          "type": "null"
        },
        "importingUser": {
          "$ref": "#/definitions/ImportingUser"
        },
        "tags": {
          "type": "array",
          "items": {}
        },
        "attributes": {
          "$ref": "#/definitions/Attributes"
        },
        "branch": {
          "type": "string"
        },
        "orgId": {
          "type": "string"
        },
        "orgName": {
          "type": "string"
        },
        "orgSlug": {
          "type": "string"
        },
        "repoCode": {
          "type": "string"
        },
        "totalSnykIssuesIncludingLicenceIssues": {
          "type": "integer",
          "description": "Total number of issues found in snyk project"
        },
        "totalSnykVulnerabilities": {
          "type": "integer",
          "description": "Total number of issues found in snyk project, excluding licence issues"
        },
        "issues": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Issue"
          }
        },
        "repoSystemData": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/RepoSystemDatum"
          }
        },
        "repoTeamCode": {
          "type": "string"
        }
      },
      "required": [
        "attributes",
        "branch",
        "browseUrl",
        "created",
        "id",
        "imageBaseImage",
        "imagePlatform",
        "imageTag",
        "importingUser",
        "isMonitored",
        "issueCountsBySeverity",
        "issues",
        "lastTestedDate",
        "name",
        "orgId",
        "orgName",
        "orgSlug",
        "origin",
        "owner",
        "readOnly",
        "repoCode",
        "repoSystemData",
        "repoTeamCode",
        "tags",
        "testFrequency",
        "totalDependencies",
        "totalSnykIssuesIncludingLicenceIssues",
        "totalSnykVulnerabilities",
        "type"
      ],
      "title": "SnykProject"
    },
    "Attributes": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "criticality": {
          "type": "array",
          "items": {}
        },
        "lifecycle": {
          "type": "array",
          "items": {}
        },
        "environment": {
          "type": "array",
          "items": {}
        }
      },
      "required": ["criticality", "environment", "lifecycle"],
      "title": "Attributes"
    },
    "ImportingUser": {
      "type": "object",
      "description": "Metadata about user who imported Snyk project",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "email": {
          "type": "string"
        }
      },
      "required": ["email", "id", "name", "username"],
      "title": "ImportingUser"
    },
    "IssueCountsBySeverity": {
      "type": "object",
      "description": "Number of findings grouped by severity that have gone pass sla - https://docs.google.com/document/d/1XXfYyNG5Qvtxb-hE7o4MhYWxZarQEe8hby38a8bOq4w",
      "additionalProperties": false,
      "properties": {
        "low": {
          "type": "integer"
        },
        "high": {
          "type": "integer"
        },
        "medium": {
          "type": "integer"
        },
        "critical": {
          "type": "integer"
        }
      },
      "required": ["critical", "high", "low", "medium"],
      "title": "IssueCountsBySeverity"
    },
    "Issue": {
      "type": "object",
      "additionalProperties": false,
      "description": "An issue is either a vulnerability or a license issue, according to the organization's policy found in Snyk",
      "properties": {
        "id": {
          "type": "string",
          "description": "The issue ID found in Snyk"
        },
        "issueType": {
          "type": "string",
          "description": "The issue type: license or vulnerability"
        },
        "pkgName": {
          "type": "string",
          "description": "The package name according to its package manager"
        },
        "pkgVersions": {
          "type": "array",
          "description": "The package version according to its package manager",
          "items": {
            "type": "string"
          }
        },
        "priorityScore": {
          "type": "integer"
        },
        "priority": {
          "$ref": "#/definitions/Priority"
        },
        "issueData": {
          "$ref": "#/definitions/IssueData"
        },
        "isPatched": {
          "type": "boolean"
        },
        "isIgnored": {
          "type": "boolean"
        },
        "fixInfo": {
          "$ref": "#/definitions/FixInfo"
        },
        "links": {
          "$ref": "#/definitions/Links"
        },
        "issueAgeDays": {
          "type": "integer"
        },
        "issueAge": {
          "type": "string"
        },
        "hasRemediation": {
          "type": "array",
          "description": "Check if there is an action to fix vulnerability found in Snyk",
          "items": {
            "type": "string"
          }
        },
        "formattedPublicationTime": {
          "type": "string"
        },
        "link": {
          "type": "string",
          "description": "URL to the issue details on snyk.io"
        },
        "severity": {
          "type": "string",
          "description": "A severity level is applied to a vulnerability, to indicate the risk for that vulnerability in an application"
        }
      },
      "required": [
        "fixInfo",
        "formattedPublicationTime",
        "hasRemediation",
        "id",
        "isIgnored",
        "isPatched",
        "issueAge",
        "issueAgeDays",
        "issueData",
        "issueType",
        "link",
        "links",
        "pkgName",
        "pkgVersions",
        "priority",
        "priorityScore",
        "severity"
      ],
      "title": "Issue"
    },
    "FixInfo": {
      "type": "object",
      "description": "Metadata on available fix found in Snyk",
      "additionalProperties": false,
      "properties": {
        "isUpgradable": {
          "type": "boolean"
        },
        "isPinnable": {
          "type": "boolean"
        },
        "isPatchable": {
          "type": "boolean"
        },
        "isFixable": {
          "type": "boolean"
        },
        "isPartiallyFixable": {
          "type": "boolean"
        },
        "nearestFixedInVersion": {
          "type": "string"
        },
        "fixedIn": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "fixedIn",
        "isFixable",
        "isPartiallyFixable",
        "isPatchable",
        "isPinnable",
        "isUpgradable",
        "nearestFixedInVersion"
      ],
      "title": "FixInfo"
    },
    "IssueData": {
      "type": "object",
      "additionalProperties": false,
      "description": "MetaData on issue found in Snyk",
      "properties": {
        "id": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "severity": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "identifiers": {
          "type": "object",
          "additionalProperties": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        },
        "credit": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "exploitMaturity": {
          "type": "string"
        },
        "semver": {
          "$ref": "#/definitions/Semver"
        },
        "publicationTime": {
          "type": "string"
        },
        "disclosureTime": {
          "type": "string"
        },
        "CVSSv3": {
          "type": "string"
        },
        "cvssScore": {
          "type": "number"
        },
        "language": {
          "type": "string"
        },
        "patches": {
          "type": "array",
          "items": {}
        },
        "nearestFixedInVersion": {
          "type": "string"
        },
        "isMaliciousPackage": {
          "type": "boolean"
        }
      },
      "required": [
        "CVSSv3",
        "credit",
        "cvssScore",
        "disclosureTime",
        "exploitMaturity",
        "id",
        "identifiers",
        "isMaliciousPackage",
        "language",
        "nearestFixedInVersion",
        "patches",
        "publicationTime",
        "semver",
        "severity",
        "title",
        "url"
      ],
      "title": "IssueData"
    },
    "Semver": {
      "type": "object",
      "additionalProperties": false,
      "description": "One or more semver (Semantic Versioning) ranges this issue is applicable to. The format varies according to package manager",
      "properties": {
        "vulnerable": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": ["vulnerable"],
      "title": "Semver"
    },
    "Links": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "paths": {
          "type": "string"
        }
      },
      "required": ["paths"],
      "title": "Links"
    },
    "Priority": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "score": {
          "type": "integer"
        },
        "factors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Factor"
          }
        }
      },
      "required": ["factors", "score"],
      "title": "Priority"
    },
    "Factor": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": {
          "type": "string"
        },
        "description": {
          "type": "string"
        }
      },
      "required": ["description", "name"],
      "title": "Factor"
    },
    "RepoSystemDatum": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        },
        "lifecycleStage": {
          "type": "string"
        },
        "serviceTier": {
          "type": "string"
        },
        "deliveredBy": {
          "$ref": "#/definitions/DeliveredBy"
        }
      },
      "required": ["code", "deliveredBy", "lifecycleStage", "serviceTier"],
      "title": "RepoSystemDatum"
    },
    "DeliveredBy": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "code": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "isThirdParty": {
          "type": "boolean"
        }
      },
      "required": ["code", "isThirdParty", "name"],
      "title": "DeliveredBy"
    },
    "FoundBy": {
      "type": "string",
      "description": "Name of scanner that found vulnerability",
      "enum": ["Nessus Scan", "Nikto Scan", "Nmap Scan", "Snyk API"],
      "title": "FoundBy"
    },
    "Severity": {
      "type": "string",
      "description": "Level of finding based on CVSS (Common Vulnerability Scoring System) score for each specific vulnerability",
      "enum": ["Medium", "Low", "Info", "Critical", "High"],
      "title": "Severity"
    }
  }
}

=== Financial-Times/vulnerability-dashboard-api-schema-public/test/data/system_valid_data.json
{
  "id": 1339,
  "code": "code-1",
  "findingsCount": 4,
  "findingsList": [143859, 146085, 1465330, 1465331],
  "teamId": 29,
  "serviceTier": "Bronze",
  "lifecycle": "production",
  "scanTypes": ["sslscan", "nmap", "nikto"],
  "findings": [
    {
      "id": 1,
      "name": "The Anti-Clickjacking X-Frame-Options Header Is Not Present.",
      "age": "7 months",
      "active": true,
      "severity": "Medium",
      "created": "2021-09-09 19:13",
      "foundBy": "Nikto Scan",
      "remediation": "N/ALook at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection , better to have a CSP.\r\nUse X-XSS-Protection: 1 as a header",
      "ageDays": 217,
      "link": "https://link/1",
      "hasRemediation": true
    },
    {
      "id": 2,
      "name": "The Anti-Clickjacking X-Frame-Options Header Is Not Present.",
      "age": "7 months",
      "active": true,
      "severity": "Medium",
      "created": "2021-09-09 18:20",
      "foundBy": "Nikto Scan",
      "remediation": "N/ALook at https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection , better to have a CSP.\r\nUse X-XSS-Protection: 1 as a header",
      "ageDays": 217,
      "link": "https://link/2",
      "hasRemediation": true
    },
    {
      "id": 3,
      "name": "Retrieved via Header: 1.1 Varnish",
      "age": "1 months 28 days",
      "active": true,
      "severity": "Info",
      "created": "2022-02-17 15:16",
      "foundBy": "Nikto Scan",
      "remediation": null,
      "ageDays": 56,
      "link": "https://link/3",
      "hasRemediation": true
    },
    {
      "id": 4,
      "name": "Retrieved X-Served-by Header: Cache-Dub4332-Dub",
      "age": "1 months 28 days",
      "active": true,
      "severity": "Info",
      "created": "2022-02-17 15:16",
      "foundBy": "Nikto Scan",
      "remediation": null,
      "ageDays": 56,
      "link": "https://link/4",
      "hasRemediation": true
    }
  ],
  "snykProjects": [],
  "matchingSnykFindingsCount": 0,
  "totalFindings": 4,
  "findingsOverSla": {}
}
